### ISSUE TITLE
Edit task

### ISSUE THREAD

**Issue by ralfw** [ralfw/todoapp#7]
A task in the table can be selected and opened on a separate edit page.
On the edit page the follwing fields can be changed:
- title
- description (multi-line text edit field)
- importance (checkbox)
- due date (date/time field, possibly with calendar)

The data is saved when pressing a "Save" button. Or editing can be cancelled. In any case the app shows the task table again.

Budget: 2 hours

**Comment by ralfw** [comment]
Editing a task works - generally. But I'm unable to enter a due date. I used the calendar control - but an exception is thrown upon saving:

<img width="330" alt="bildschirmfoto 2015-07-12 um 14 31 16" src="https://cloud.githubusercontent.com/assets/132662/8637757/fe789a64-28a2-11e5-8417-f323f8839738.png">

<img width="946" alt="bildschirmfoto 2015-07-12 um 14 30 04" src="https://cloud.githubusercontent.com/assets/132662/8637758/07d00750-28a3-11e5-82d5-3dd3dae20c1c.png">

If the date/time format is depending on my cultureinfo, then there's still something wrong. I'm unable to enter a date in the German format, e.g. 12.7.2015 for today.

**Comment by CannyDoersolutions** [comment]
resolved.... now can you check and let me know ?

**Comment by ralfw** [comment]
Sorry, the app is broken now. Won't even start. When I press F5 this error appears:

<img width="878" alt="bildschirmfoto 2015-07-12 um 18 51 06" src="https://cloud.githubusercontent.com/assets/132662/8638828/22df84c0-28c7-11e5-8a89-1b57bc3be27e.png">

Up to now I never had a problem starting the app.

**Comment by ralfw** [comment]
I'm still unable to enter a date in my form with "." as a delimiter.

If I select a date from the calendar the task can be saved now. But the format is wrong:

<img width="224" alt="bildschirmfoto 2015-07-12 um 19 00 03" src="https://cloud.githubusercontent.com/assets/132662/8638868/68854270-28c8-11e5-989b-09e3fa384f4c.png">

It's mm.dd.yyyy, but it should be dd.mm.yyyy. Also I don't want to see "nachm." instead of "pm". A 24h time should be displayed (2pm = 14:00).

**Comment by CannyDoersolutions** [comment]
Ok try now....

**Comment by ralfw** [comment]
Display in table looks ok now. But entering a date does not work well.

If I select a date from the calendar, its format is different from the display format. Not good.

<img width="335" alt="bildschirmfoto 2015-07-12 um 19 50 26" src="https://cloud.githubusercontent.com/assets/132662/8639101/c9c9c608-28cf-11e5-918a-52b744b7aa3c.png">

When I open the edit page on a task with a date, the date is displayed differently. Not good.

<img width="309" alt="bildschirmfoto 2015-07-12 um 19 55 00" src="https://cloud.githubusercontent.com/assets/132662/8639111/fd388e5c-28cf-11e5-97d0-9387f84c4238.png">

Entering a date like "3/2/2010 9:59" causes an exception. Not good.

Accidentally I saw your date parsing code:

<img width="678" alt="bildschirmfoto 2015-07-12 um 19 57 15" src="https://cloud.githubusercontent.com/assets/132662/8639118/40967ec0-28d0-11e5-8220-d42e9ee51c26.png">

Sorry, man, this does not look right. Why don't you let DateTime.Parse() let do the work? Of course depending on the right culture? Have a look at this spike solution in the repo: https://github.com/ralfw/todoapp/blob/master/src/spikes/ralfw/scratchpad_tests/Test.cs
No manual parsing of date/time string.

**Comment by CannyDoersolutions** [comment]
well the issue is storing date in SQLite for this format so that Code that you have seen that is to store the date in Database Format 
the issue has been fixed now can u give it a try now ?

**Comment by ralfw** [comment]
Thx for trying again. But it's not working yet :-(

It crashes, if I try to edit a task without a due date.
It crashes, if I enter some dates. (Haven't identified the pattern yet.)

<img width="995" alt="bildschirmfoto 2015-07-13 um 07 07 13" src="https://cloud.githubusercontent.com/assets/132662/8643076/000cf56e-292f-11e5-93c1-22d8bae7c01c.png">
<img width="693" alt="bildschirmfoto 2015-07-13 um 07 08 54" src="https://cloud.githubusercontent.com/assets/132662/8643075/000a31a8-292f-11e5-8687-befb0feff037.png">

**Comment by ralfw** [comment]
Storing any date should be no problem. SQlite for sure offer a date/time column type to which you can assign DateTime objects.

**Comment by CannyDoersolutions** [comment]
Try now this time i hope it should work without any issue

**Comment by CannyDoersolutions** [comment]
and also storing Datetime is not a Problem the Probelm is with there Format to store in SQlite through Code it sshould be in 'yyyy-mm-dd HH:mm' format other wise throws exception

**Comment by ralfw** [comment]
Works much better now. I was able to enter dates in the past and in the future and even delete a due date.

But entering a date without a time did not work. If there is no time given, you should assume the start of the day, e.g. 6am or midnight (0am?).

**Comment by ralfw** [comment]
Why should storing da DateTime value be a problem. Once you have the due date converted from text to a DateTime value, then you can serialize it into any format. Here's a suggestion regarding SQlite: http://techreadme.blogspot.de/2012/11/sqlite-read-write-datetime-values-using.html

**Comment by CannyDoersolutions** [comment]
ok so for that without time i have to check the things 
if you want that as well i will include that logic otherwise working fine ?

**Comment by CannyDoersolutions** [comment]
try now i have updated by your suggestion

**Comment by ralfw** [comment]
Entering due dates is working fine for now. I don't mind the hard coded de-de culture.
